name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      project: Photino.NET/Photino.NET.csproj
      nugetFolder: ./nuget
      configuration: Debug
      repository: "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    steps:
      - run: |
          echo ${{ env.project }}
          echo ${{ env.nugetFolder }}
          echo ${{ env.configuration }}

      - uses: actions/checkout@v2

      - name: Unshallow Fetch
        run: git fetch --unshallow

      - name: Setup .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: ${{ env.repository }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, Pack and Publish to GitHub
        run: |
          gpr="GPR"
          user="${{ github.repository_owner }}"
          pw="${{ secrets.GITHUB_TOKEN }}"
          source="${{ env.repository }}"
          nugetFolder=${{ env.nugetFolder }}
          project=${{ env.project }}
          configuration=${{ env.configuration }}

          mkdir $nugetFolder 

          dotnet restore $project 

          dotnet pack --configuration $configuration --no-restore --include-symbols --include-source --output $nugetFolder $project

      - name: PushGithub
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nugetDir="/home/runner/nuget"
          
          mkdir $nugetDir
          cp -r /home/runner/.nuget/packages/nuget.commandline.xplat/5.9.0/lib/net5.0/* $nugetDir/ 
          cp -r /home/runner/.nuget/packages/nuget.commands/5.9.0/lib/net5.0/* $nugetDir/ 
          cp -r /home/runner/.nuget/packages/nuget.protocol/5.9.0/lib/net5.0/* $nugetDir/ 
          cp -r /home/runner/.nuget/packages/nuget.packaging/5.9.0/lib/net5.0/* $nugetDir/
          cp -r /home/runner/.nuget/packages/nuget.versioning/5.9.0/lib/netstandard2.0/* $nugetDir/
          cp -r /home/runner/.nuget/packages/nuget.common/5.9.0/lib/netstandard2.0/* $nugetDir/ 
          cp -r /home/runner/.nuget/packages/nuget.configuration/5.9.0/lib/netstandard2.0/* $nugetDir/ 

          cp -r /home/runner/.nuget/packages/nuget.credentials/5.9.0/lib/net5.0/* $nugetDir/ 
          cp -r /home/runner/.nuget/packages/nuget.dependencyresolver.core/5.9.0/lib/net5.0/* $nugetDir/ 
          cp -r /home/runner/.nuget/packages/nuget.frameworks/5.9.0/lib/netstandard2.0/* $nugetDir/ 
          cp -r /home/runner/.nuget/packages/nuget.librarymodel/5.9.0/lib/netstandard2.0/* $nugetDir/ 
          cp -r /home/runner/.nuget/packages/nuget.projectmodel/5.9.0/lib/net5.0/* $nugetDir/ 

          cp -r /home/runner/.nuget/packages/newtonsoft.json/9.0.1/lib/netstandard1.0/* $nugetDir/
          cp -r /home/runner/.nuget/packages/microsoft.extensions.commandlineutils/1.1.1/lib/netstandard1.3/* $nugetDir/
          cp -r /home/runner/.nuget/packages/netstandard.library/2.0.3/build/netstandard2.0/ref/* $nugetDir/
          
          nuget="$nugetDir/NuGet.CommandLine.XPlat.dll"

          dotnet $nuget push ${{ env.nugetFolder }}/*.nupkg --no-symbols --skip-duplicate

#        dpkg-deb -xv {$deb} {.}

#        for package in $nugetFolder/*.nupkg
#        do
#          echo $package
#          curl -vX PUT -u "$user:$pw" -F package=@$package $source;
#        done;
    
