name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      project: Photino.NET/Photino.NET.csproj
      nugetFolder: ./nuget
      configuration: Debug
      repository: "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    steps:
      - run: |
          echo ${{ env.project }}
          echo ${{ env.nugetFolder }}
          echo ${{ env.configuration }}

      - uses: actions/checkout@v2

      - name: Unshallow Fetch
        run: git fetch --unshallow

      - name: Setup .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: ${{ env.repository }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore
        run: |
          nugetPath="/home/runner/nuget.exe"
          curl https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o $nugetPath 

          chmod +x $nugetPath 

          project=${{ env.project }}

          dotnet restore $project 


      - name: Build, Pack and Publish to GitHub
        run: |
          nugetFolder=${{ env.nugetFolder }}
          project=${{ env.project }}
          configuration=${{ env.configuration }}

          mkdir $nugetFolder 

          dotnet pack --configuration $configuration --no-restore --include-symbols --include-source --output $nugetFolder $project

      - name: Push Github
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gpr="GPR"
          user="${{ github.repository_owner }}"
          pw="${{ secrets.GITHUB_TOKEN }}"
          source="${{ env.repository }}"

          /home/runner/nuget.exe setApiKey ${{ secrets.GITHUB_TOKEN }} -src ${{ env.repository }}

          for package in $nugetFolder/*.nupkg
          do
              echo "/home/runner/nuget.exe push $package ${{ secrets.GITHUB_TOKEN }} -src ${{ env.repository }} -NoSymbols -SkipDuplicate" 
              /home/runner/nuget.exe push $package ${{ secrets.GITHUB_TOKEN }} -src ${{ env.repository }} -NoSymbols -SkipDuplicate
          done;

#               nugetDir="/home/runner/nuget"
#
#               mkdir $nugetDir
#               cp -r /home/runner/.nuget/packages/nuget.commandline.xplat/5.9.0/lib/net5.0/* $nugetDir/
#               cp -r /home/runner/.nuget/packages/nuget.commands/5.9.0/lib/net5.0/* $nugetDir/
#               cp -r /home/runner/.nuget/packages/nuget.protocol/5.9.0/lib/net5.0/* $nugetDir/
#               cp -r /home/runner/.nuget/packages/nuget.packaging/5.9.0/lib/net5.0/* $nugetDir/
#               cp -r /home/runner/.nuget/packages/nuget.versioning/5.9.0/lib/netstandard2.0/* $nugetDir/
#               cp -r /home/runner/.nuget/packages/nuget.common/5.9.0/lib/netstandard2.0/* $nugetDir/
#               cp -r /home/runner/.nuget/packages/nuget.configuration/5.9.0/lib/netstandard2.0/* $nugetDir/
#
#               cp -r /home/runner/.nuget/packages/nuget.credentials/5.9.0/lib/net5.0/* $nugetDir/
#               cp -r /home/runner/.nuget/packages/nuget.dependencyresolver.core/5.9.0/lib/net5.0/* $nugetDir/
#               cp -r /home/runner/.nuget/packages/nuget.frameworks/5.9.0/lib/netstandard2.0/* $nugetDir/
#               cp -r /home/runner/.nuget/packages/nuget.librarymodel/5.9.0/lib/netstandard2.0/* $nugetDir/
#               cp -r /home/runner/.nuget/packages/nuget.projectmodel/5.9.0/lib/net5.0/* $nugetDir/
#
#               cp -r /home/runner/.nuget/packages/newtonsoft.json/9.0.1/lib/netstandard1.0/* $nugetDir/
#               cp -r /home/runner/.nuget/packages/microsoft.extensions.commandlineutils/1.1.1/lib/netstandard1.3/* $nugetDir/
#               cp -r /home/runner/.nuget/packages/netstandard.library/2.0.3/build/netstandard2.0/ref/* $nugetDir/
