name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      project: Photino.NET/Photino.NET.csproj
      nugetFolder: ./nuget
      configuration: Debug

    steps:
    - run: |
        echo ${{ env.project }}
        echo ${{ env.nugetFolder }}
        echo ${{ env.configuration }}

    - uses: actions/checkout@v2

    - name: Unshallow Fetch
      run: git fetch --unshallow

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        dotnet-version: 5.0.x
        source-url: 'https://nuget.pkg.github.com/sharpninja/index.json'

    - name: Build, Pack and Publish to GitHub
      run: |
        mkdir ${{ env.nugetFolder }}
        
        dotnet restore ${{ env.project }}
        
        dotnet pack --configuration ${{ env.configuration }} --no-restore --include-symbols --include-source --output ${{ env.nugetFolder }} ${{ env.project }}
        
        ls -l ${{ env.nugetFolder }} 

        dotnet nuget push ${{ env.nugetFolder }}/*.nupkg --skip-duplicate --no-symbols true
        
#        nuget source Add -Name "GitHub" -Source ${{ env.nugetRepository }}
#        nuget setApiKey ${{ env.token }} -src ${{ env.nugetRepository }}  
#        nuget push ${{ env.nugetFolder }}/*.nupkg -src "GitHub"
        