name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      project: Photino.NET/Photino.NET.csproj
      nugetConfig: ./.github/workflows/nuget.config
      nugetFolder: ./nuget
      configuration: Debug
      token: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - run: |
        echo ${{ env.project }}
        echo ${{ env.nugetConfig }}
        echo ${{ env.nugetFolder }}
        echo ${{ env.token }}

        if [ ${{ env.token }} -eq "" ] {
          echo "Empty token." 1>&2
          exit 64
        }
    - uses: actions/checkout@v2

    - name: Unshallow Fetch
      run: git fetch --unshallow

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.configuration }} --no-restore ${{ env.project }} 

    - name: Pack Nuget Package
      run: |
        mkdir ${{ env.nugetFolder }}
        dotnet pack --configuration ${{ env.configuration }} --no-restore --include-symbols --include-source --output ${{ env.nugetFolder }} ${{ env.project }}

    - name: Publish
      run: |
        sed -i 's/\$GITHUBACTIONS/${{ env.token }}/g' ${{ env.nugetConfig }}
        nuget push ${{ env.nugetFolder }}/*.nupkg -src 'github' -ConfigFile ${{ env.nugetConfig }}
        