name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    with:
    - project: Photino.NET/Photino.NET.csproj
    - nugetConfig: ./.github/workflows/nuget.config
    - nugetFolder: ./nuget

    steps:
    - run: |
        echo $project
        echo $nugetConfig
        echo $nugetFolder
    - uses: actions/checkout@v2

    - name: Unshallow Fetch
      run: git fetch --unshallow

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug --no-restore $project 

    - name: Pack Nuget Package
      run: |
        mkdir $nugetFolder
        dotnet pack --configuration Debug --no-restore --include-symbols --include-source --output $nugetFolder $project

    - name: Publish
      run: |
        sed -i 's/\$GITHUBACTIONS/${{ secrets.GITUHUB_TOKEN }}/g' $nugetConfig
        nuget push $nugetFolder/*.nupkg -src 'github' -ConfigFile $nugetConfig
        