name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
#    outputs:
#      semVer: ${{ steps.gitversion.outputs.semVer }}

    steps:
    - uses: actions/checkout@v2

    - name: Unshallow Fetch
      run: git fetch --unshallow

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

#    - name: Install GitVersion
#      uses: gittools/actions/gitversion/setup@v0.9.7
#      with:
#        versionSpec: '5.x'
#        includePrerelease: true
#
#    - name: Determine Version
#      id: gitversion
#      uses: gittools/actions/gitversion/execute@v0.9.7
#      with:
#        useConfigFile: true
#        configFilePath: .github/workflows/gitversion.yml
#        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug --no-restore Photino.NET/Photino.NET.csproj 

    - name: Pack Nuget Package
      run: mkdir ./nuget; dotnet pack --configuration Debug --no-restore --include-symbols --include-source --output ./nuget Photino.NET/Photino.NET.csproj

    - name: Push Nuget Package
      run: cd ./nuget; nuget push *.nupkg ${{ secrets.GITHUB_TOKEN }} -src https://nuget.pkg.github.com/${{ github.actor }}/index.json  
