name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --verbosity normal
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@latest
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: ${{ GITHUB_WORKSPACE }}/Photino.NET/Photino.NET.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}
        # NuGet server uri hosting the packages, defaults to https://api.nuget.org
        NUGET_SOURCE: https://nuget.pkg.github.com/${{ GITHUB_ACTOR }}/index.json
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true
